# Configuration for GitHub's automatic release notes generation
# Documentation: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - invalid
      - wontfix
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat

    - title: Bug Fixes
      labels:
        - bug
        - fix
        - bugfix

    - title: Documentation
      labels:
        - documentation
        - docs

    - title: Maintenance & Chores
      labels:
        - chore
        - maintenance
        - refactor
        - ci
        - workflow

    - title: Security
      labels:
        - security

    - title: Performance
      labels:
        - performance
        - perf

    - title: Other Changes
      labels:
        - "*"